<?php

namespace Intex\OrgBundle\Entity\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return users from array $users that not exist in DB
     * @param ArrayCollection $users
     * @return array
     */
    public function getNewUsers(ArrayCollection $users)
    {
        $usersInns = $this->getInn($users);

        $db = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.inn IN (:inns)')
            ->setParameter('inns', $usersInns);

        $existingUsers = $db->getQuery()->getResult();

        return $this->getArrayDiffUsers($users, $existingUsers);
    }

    /**
     * Return users from array $users which do not exist in array $existingUsers
     * @param ArrayCollection $users
     * @param ArrayCollection $existingUsers
     * @return array
     */
    protected function getArrayDiffUsers(ArrayCollection $users, $existingUsers)
    {
        $usersInns = $this->getInn($users);
        $existingInns = $this->getInn($existingUsers);

        $newInns = array_diff($usersInns, $existingInns);

        $newUsers = array();
        if ($newInns) {
            foreach ($users as $human) {
                if (in_array($human->getInn(), $newInns)){
                    $newUsers[] = $human;
                }
            }
        }

        return $newUsers;
    }

    /**
     * Return INN(Insurance Number of Individual Ledger Account user's) users from array $users
     * @param ArrayCollection $users
     * @return array
     */
    protected function getInn($users)
    {
        $usersInns = array();

        foreach ($users as $human){
            $usersInns[] = $human->getInn();
        }

        return $usersInns;
    }
}
